### ISSUE TITLE
Resolve conflict with nuxt ^3.0.0

### ISSUE THREAD

**Issue by m-negahi** [FrontLabsOfficial/vue-tiny-validate#23]
Look like composition-api version has conflict.

![Screenshot 2023-01-22 122309](https://user-images.githubusercontent.com/19972901/213907716-3d2b1ab2-3a7c-4ee4-b2f8-21bf8ff1d315.png)

**Comment by anh-ld** [comment]
Thanks @kindslayer for letting me know about that. This is probably a typical Nuxt 3 issue. Please try using instead:

```
npm install vue-tiny-validate --legacy-peer-deps
```
