### ISSUE TITLE
Pass a second parameter to the test function containing the root state

### ISSUE THREAD

**Issue by SharpSeeEr** [FrontLabsOfficial/vue-tiny-validate#3]
The test function should accept an optional second argument containing the root state, just for flexibility. This would make it easier to create reusable validators that compare two different variables, e.g. requiredIf, requiredIfValue.

**Comment by anh-ld** [comment]
Good idea. I am gonna implement it in the next release. Or any pull requests from you are also welcomed.

Thanks man.

**Comment by anh-ld** [comment]
Updated #6
