### ISSUE TITLE
Support for @vue/composition-api

### ISSUE THREAD

**Issue by kenneth-hendricks** [FrontLabsOfficial/vue-tiny-validate#5]
Hi,

Really interested in this plugin, it would be great to have support for the Vue2 composition-api, are there any plans to implement this ?

Cheers

**Comment by anh-ld** [comment]
Hi @kenneth-hendricks, sorry for my late reply.

Technically, it does support Vue 2 composition api (with Vue v2.6 or above). However, I haven't tested yet to check whether it works or not.

The next release will certainly support Vue composition. (will be released in the next week).

Thanks.

**Comment by kenneth-hendricks** [comment]
Sorry I should have added more details, when using this with the Vue2 composition API, the plugin fails when trying to import `reactive` from vue. 

I believe in the case of using the vue2 composition api you need to import directly from the composition api package, hence why some packages are using vue-demi (https://github.com/vueuse/vue-demi).

**Comment by anh-ld** [comment]
Oh, I just have forgetten it! Thank you @kenneth-hendricks for letting me know this. 🙏

**Comment by anh-ld** [comment]
Updated #6
